#!/usr/bin/env bash

set -e
set -x

function config_hosts(){
  echo "Configuring /etc/hosts ..."
  echo "192.168.31.100 dc1.mongodb.university dc1"   >> /etc/hosts
  echo "192.168.31.200 dc2.mongodb.university dc2"   >> /etc/hosts
}

function update_repo(){
  echo "Install MongoDB Enterprise Repository"
  echo "deb [ arch=amd64 ] http://repo.mongodb.com/apt/ubuntu trusty/mongodb-enterprise/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-enterprise.list
  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
  echo "Update Repositories"
  apt-get update -y
  apt-get install -y mongodb-enterprise mtools
}

function install_mongod(){
  echo "Install MongoDB Enterprise"
  apt-get install -y mongodb-enterprise
  sh -c "killall mongod; true"
  echo "Set LC_ALL=C to .profile"
  echo "export LC_ALL=C" >> /home/vagrant/.profile
}

function config(){
  # disable THP
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/enabled
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/defrag
  # disable mongod upstart service
  echo 'manual' | tee /etc/init/mongod.override
}

config_hosts
update_repo
install_mongod
config
echo "DONE"
